import type { ITheme } from "@xterm/xterm";

export interface TerminalThemePreset {
  id: string;
  name: string;
  /** A short description shown under the name in the picker. */
  blurb: string;
  /** undefined for the "app" preset, which follows the app's light/dark
   * mode + accent color (the CSS custom properties in global.css) instead
   * of a fixed palette. */
  theme?: ITheme;
}

/**
 * Curated, named terminal color themes. Besides the default "follow the
 * app theme" option, these are static palettes independent of the
 * light/dark app chrome — several (Solarized, Nord, Gruvbox, Sepia) are
 * specifically chosen for being low-contrast and easy on the eyes for long
 * terminal sessions; a few higher-contrast, more vibrant options (Dracula,
 * One Dark, Tokyo Night, Monokai) are included for people who prefer that.
 * Palette values are the well-known published hex codes for each scheme.
 */
export const TERMINAL_THEME_PRESETS: TerminalThemePreset[] = [
  {
    id: "app",
    name: "Match App Theme",
    blurb: "Follows light/dark mode + accent color",
  },
  {
    id: "solarized-dark",
    name: "Solarized Dark",
    blurb: "Muted, low-contrast — easy on the eyes",
    theme: {
      background: "#002b36",
      foreground: "#839496",
      cursor: "#839496",
      selectionBackground: "rgba(131, 148, 150, 0.25)",
      black: "#073642",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
      brightBlack: "#002b36",
      brightRed: "#cb4b16",
      brightGreen: "#586e75",
      brightYellow: "#657b83",
      brightBlue: "#839496",
      brightMagenta: "#6c71c4",
      brightCyan: "#93a1a1",
      brightWhite: "#fdf6e3",
    },
  },
  {
    id: "solarized-light",
    name: "Solarized Light",
    blurb: "Warm paper tone — soft daytime reading",
    theme: {
      background: "#fdf6e3",
      foreground: "#657b83",
      cursor: "#657b83",
      selectionBackground: "rgba(101, 123, 131, 0.2)",
      black: "#073642",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
      brightBlack: "#002b36",
      brightRed: "#cb4b16",
      brightGreen: "#586e75",
      brightYellow: "#657b83",
      brightBlue: "#839496",
      brightMagenta: "#6c71c4",
      brightCyan: "#93a1a1",
      brightWhite: "#fdf6e3",
    },
  },
  {
    id: "nord",
    name: "Nord",
    blurb: "Cool arctic blues — calm and quiet",
    theme: {
      background: "#2e3440",
      foreground: "#d8dee9",
      cursor: "#d8dee9",
      selectionBackground: "rgba(136, 192, 208, 0.25)",
      black: "#3b4252",
      red: "#bf616a",
      green: "#a3be8c",
      yellow: "#ebcb8b",
      blue: "#81a1c1",
      magenta: "#b48ead",
      cyan: "#88c0d0",
      white: "#e5e9f0",
      brightBlack: "#4c566a",
      brightRed: "#bf616a",
      brightGreen: "#a3be8c",
      brightYellow: "#ebcb8b",
      brightBlue: "#81a1c1",
      brightMagenta: "#b48ead",
      brightCyan: "#8fbcbb",
      brightWhite: "#eceff4",
    },
  },
  {
    id: "gruvbox-dark",
    name: "Gruvbox Dark",
    blurb: "Warm retro tones — gentle contrast",
    theme: {
      background: "#282828",
      foreground: "#ebdbb2",
      cursor: "#ebdbb2",
      selectionBackground: "rgba(235, 219, 178, 0.2)",
      black: "#282828",
      red: "#cc241d",
      green: "#98971a",
      yellow: "#d79921",
      blue: "#458588",
      magenta: "#b16286",
      cyan: "#689d6a",
      white: "#a89984",
      brightBlack: "#928374",
      brightRed: "#fb4934",
      brightGreen: "#b8bb26",
      brightYellow: "#fabd2f",
      brightBlue: "#83a598",
      brightMagenta: "#d3869b",
      brightCyan: "#8ec07c",
      brightWhite: "#ebdbb2",
    },
  },
  {
    id: "sepia",
    name: "Sepia",
    blurb: "Warm dark paper — designed for long sessions",
    theme: {
      background: "#2b2420",
      foreground: "#d8c9a3",
      cursor: "#d8c9a3",
      selectionBackground: "rgba(216, 201, 163, 0.22)",
      black: "#2b2420",
      red: "#c26b52",
      green: "#9caf6f",
      yellow: "#d8ad4d",
      blue: "#7c9885",
      magenta: "#b98a9a",
      cyan: "#8bab97",
      white: "#d8c9a3",
      brightBlack: "#5c5044",
      brightRed: "#d98b6f",
      brightGreen: "#b3c78a",
      brightYellow: "#e8c579",
      brightBlue: "#93ad9c",
      brightMagenta: "#cba3b2",
      brightCyan: "#a3c2ae",
      brightWhite: "#f0e6cc",
    },
  },
  {
    id: "dracula",
    name: "Dracula",
    blurb: "Vibrant purples — popular and punchy",
    theme: {
      background: "#282a36",
      foreground: "#f8f8f2",
      cursor: "#f8f8f2",
      selectionBackground: "rgba(68, 71, 90, 0.7)",
      black: "#21222c",
      red: "#ff5555",
      green: "#50fa7b",
      yellow: "#f1fa8c",
      blue: "#bd93f9",
      magenta: "#ff79c6",
      cyan: "#8be9fd",
      white: "#f8f8f2",
      brightBlack: "#6272a4",
      brightRed: "#ff6e6e",
      brightGreen: "#69ff94",
      brightYellow: "#ffffa5",
      brightBlue: "#d6acff",
      brightMagenta: "#ff92df",
      brightCyan: "#a4ffff",
      brightWhite: "#ffffff",
    },
  },
  {
    id: "one-dark",
    name: "One Dark",
    blurb: "The Atom classic — balanced and familiar",
    theme: {
      background: "#282c34",
      foreground: "#abb2bf",
      cursor: "#528bff",
      selectionBackground: "rgba(171, 178, 191, 0.2)",
      black: "#282c34",
      red: "#e06c75",
      green: "#98c379",
      yellow: "#e5c07b",
      blue: "#61afef",
      magenta: "#c678dd",
      cyan: "#56b6c2",
      white: "#abb2bf",
      brightBlack: "#5c6370",
      brightRed: "#e06c75",
      brightGreen: "#98c379",
      brightYellow: "#e5c07b",
      brightBlue: "#61afef",
      brightMagenta: "#c678dd",
      brightCyan: "#56b6c2",
      brightWhite: "#ffffff",
    },
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    blurb: "Deep indigo city lights",
    theme: {
      background: "#1a1b26",
      foreground: "#c0caf5",
      cursor: "#c0caf5",
      selectionBackground: "rgba(65, 72, 104, 0.6)",
      black: "#15161e",
      red: "#f7768e",
      green: "#9ece6a",
      yellow: "#e0af68",
      blue: "#7aa2f7",
      magenta: "#bb9af7",
      cyan: "#7dcfff",
      white: "#a9b1d6",
      brightBlack: "#414868",
      brightRed: "#f7768e",
      brightGreen: "#9ece6a",
      brightYellow: "#e0af68",
      brightBlue: "#7aa2f7",
      brightMagenta: "#bb9af7",
      brightCyan: "#7dcfff",
      brightWhite: "#c0caf5",
    },
  },
  {
    id: "monokai",
    name: "Monokai",
    blurb: "Classic editor look — bold and saturated",
    theme: {
      background: "#272822",
      foreground: "#f8f8f2",
      cursor: "#f8f8f0",
      selectionBackground: "rgba(248, 248, 242, 0.2)",
      black: "#272822",
      red: "#f92672",
      green: "#a6e22e",
      yellow: "#f4bf75",
      blue: "#66d9ef",
      magenta: "#ae81ff",
      cyan: "#a1efe4",
      white: "#f8f8f2",
      brightBlack: "#75715e",
      brightRed: "#f92672",
      brightGreen: "#a6e22e",
      brightYellow: "#f4bf75",
      brightBlue: "#66d9ef",
      brightMagenta: "#ae81ff",
      brightCyan: "#a1efe4",
      brightWhite: "#f9f8f5",
    },
  },
  {
    id: "gruvbox-light",
    name: "Gruvbox Light",
    blurb: "Retro warm paper tone — daytime pair to Gruvbox Dark",
    theme: {
      background: "#fbf1c7",
      foreground: "#3c3836",
      cursor: "#3c3836",
      selectionBackground: "rgba(60, 56, 54, 0.2)",
      black: "#fbf1c7",
      red: "#cc241d",
      green: "#98971a",
      yellow: "#d79921",
      blue: "#458588",
      magenta: "#b16286",
      cyan: "#689d6a",
      white: "#7c6f64",
      brightBlack: "#928374",
      brightRed: "#9d0006",
      brightGreen: "#79740e",
      brightYellow: "#b57614",
      brightBlue: "#076678",
      brightMagenta: "#8f3f71",
      brightCyan: "#427b58",
      brightWhite: "#3c3836",
    },
  },
  {
    id: "one-light",
    name: "One Light",
    blurb: "Clean, high-contrast daytime pair to One Dark",
    theme: {
      background: "#fafafa",
      foreground: "#383a42",
      cursor: "#383a42",
      selectionBackground: "rgba(56, 58, 66, 0.15)",
      black: "#383a42",
      red: "#e45649",
      green: "#50a14f",
      yellow: "#c18401",
      blue: "#4078f2",
      magenta: "#a626a4",
      cyan: "#0184bc",
      white: "#fafafa",
      brightBlack: "#a0a1a7",
      brightRed: "#e45649",
      brightGreen: "#50a14f",
      brightYellow: "#c18401",
      brightBlue: "#4078f2",
      brightMagenta: "#a626a4",
      brightCyan: "#0184bc",
      brightWhite: "#ffffff",
    },
  },
  {
    id: "catppuccin-mocha",
    name: "Catppuccin Mocha",
    blurb: "Soft pastel dark — a popular, gentle-on-the-eyes palette",
    theme: {
      background: "#1e1e2e",
      foreground: "#cdd6f4",
      cursor: "#f5e0dc",
      selectionBackground: "rgba(205, 214, 244, 0.2)",
      black: "#45475a",
      red: "#f38ba8",
      green: "#a6e3a1",
      yellow: "#f9e2af",
      blue: "#89b4fa",
      magenta: "#f5c2e7",
      cyan: "#94e2d5",
      white: "#bac2de",
      brightBlack: "#585b70",
      brightRed: "#f38ba8",
      brightGreen: "#a6e3a1",
      brightYellow: "#f9e2af",
      brightBlue: "#89b4fa",
      brightMagenta: "#f5c2e7",
      brightCyan: "#94e2d5",
      brightWhite: "#a6adc8",
    },
  },
  {
    id: "catppuccin-latte",
    name: "Catppuccin Latte",
    blurb: "Pastel light — the daytime Catppuccin flavor",
    theme: {
      background: "#eff1f5",
      foreground: "#4c4f69",
      cursor: "#dc8a78",
      selectionBackground: "rgba(76, 79, 105, 0.15)",
      black: "#5c5f77",
      red: "#d20f39",
      green: "#40a02b",
      yellow: "#df8e1d",
      blue: "#1e66f5",
      magenta: "#ea76cb",
      cyan: "#179299",
      white: "#acb0be",
      brightBlack: "#6c6f85",
      brightRed: "#d20f39",
      brightGreen: "#40a02b",
      brightYellow: "#df8e1d",
      brightBlue: "#1e66f5",
      brightMagenta: "#ea76cb",
      brightCyan: "#179299",
      brightWhite: "#bcc0cc",
    },
  },
  {
    id: "rose-pine",
    name: "Rosé Pine",
    blurb: "Muted rose & pine — quiet, low-saturation dark theme",
    theme: {
      background: "#191724",
      foreground: "#e0def4",
      cursor: "#e0def4",
      selectionBackground: "rgba(224, 222, 244, 0.2)",
      black: "#26233a",
      red: "#eb6f92",
      green: "#31748f",
      yellow: "#f6c177",
      blue: "#9ccfd8",
      magenta: "#c4a7e7",
      cyan: "#ebbcba",
      white: "#e0def4",
      brightBlack: "#6e6a86",
      brightRed: "#eb6f92",
      brightGreen: "#31748f",
      brightYellow: "#f6c177",
      brightBlue: "#9ccfd8",
      brightMagenta: "#c4a7e7",
      brightCyan: "#ebbcba",
      brightWhite: "#e0def4",
    },
  },
];

export const DEFAULT_TERMINAL_THEME_ID = "app";

export function getTerminalThemePreset(id: string): TerminalThemePreset {
  return TERMINAL_THEME_PRESETS.find((p) => p.id === id) ?? TERMINAL_THEME_PRESETS[0];
}

const TERM_CSS_VARS = [
  ["background", "--term-bg"],
  ["foreground", "--term-fg"],
  ["cursor", "--term-cursor"],
  ["selectionBackground", "--term-selection"],
  ["black", "--term-black"],
  ["red", "--term-red"],
  ["green", "--term-green"],
  ["yellow", "--term-yellow"],
  ["blue", "--term-blue"],
  ["magenta", "--term-magenta"],
  ["cyan", "--term-cyan"],
  ["white", "--term-white"],
  ["brightBlack", "--term-bright-black"],
  ["brightRed", "--term-bright-red"],
  ["brightGreen", "--term-bright-green"],
  ["brightYellow", "--term-bright-yellow"],
  ["brightBlue", "--term-bright-blue"],
  ["brightMagenta", "--term-bright-magenta"],
  ["brightCyan", "--term-bright-cyan"],
  ["brightWhite", "--term-bright-white"],
] as const;

/** Builds an xterm.js theme from the current CSS custom properties, so the
 * terminal's colors are a single source of truth (global.css) rather than
 * duplicated as hex literals in JS. Used for the "Match App Theme" preset. */
export function readAppCssTheme(): ITheme {
  const styles = getComputedStyle(document.documentElement);
  const theme: Record<string, string> = {};
  for (const [key, cssVar] of TERM_CSS_VARS) {
    const value = styles.getPropertyValue(cssVar).trim();
    if (value) theme[key] = value;
  }
  return theme;
}

/** Resolves the active xterm theme: a fixed preset palette, or (for the
 * "app" preset) the app's own light/dark + accent CSS custom properties. */
export function resolveXtermTheme(themeId: string): ITheme {
  const preset = getTerminalThemePreset(themeId);
  return preset.theme ?? readAppCssTheme();
}
