#!/usr/bin/env node
/**
 * Issues a signed Wharf license key for local testing, using the dev
 * signing key generated by `npm run license:generate-keys`.
 *
 * This is a stand-in for a real license-issuance backend: in production
 * you'd run equivalent signing logic server-side (e.g. triggered by a
 * successful payment), never ship the private key, and never let end
 * users run this script against your real signing key.
 *
 * Usage:
 *   node scripts/generate-license.mjs --email you@example.com [options]
 *
 * Options:
 *   --email <email>       required
 *   --plan <free|pro>     default: pro
 *   --seats <n>           default: 1
 *   --days <n>            expire N days from now (default: perpetual)
 *   --features <a,b,c>    comma-separated FeatureId list (default: all pro features)
 */
import { createPrivateKey, sign as cryptoSign, randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const privateKeyPath = path.join(__dirname, "..", "keys", "license-signing-key.private.json");

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i].startsWith("--")) {
      const key = argv[i].slice(2);
      const value = argv[i + 1] && !argv[i + 1].startsWith("--") ? argv[++i] : "true";
      args[key] = value;
    }
  }
  return args;
}

const args = parseArgs(process.argv.slice(2));

if (!args.email) {
  console.error("Missing required --email <email>\n");
  console.error("Usage: node scripts/generate-license.mjs --email you@example.com [--plan pro] [--seats 1] [--days 365] [--features unlimitedHosts,portForwarding]");
  process.exit(1);
}

let privateKeyRecord;
try {
  privateKeyRecord = JSON.parse(readFileSync(privateKeyPath, "utf8"));
} catch {
  console.error(`Could not read ${privateKeyPath}.`);
  console.error("Run `npm run license:generate-keys` first.");
  process.exit(1);
}

const privateKey = createPrivateKey(privateKeyRecord.privateKeyPem);

const plan = args.plan === "free" ? "free" : "pro";
const allProFeatures = ["unlimitedHosts", "unlimitedGroups", "portForwarding", "jumpHosts", "teamSync"];
const features = args.features ? args.features.split(",").map((f) => f.trim()).filter(Boolean) : plan === "pro" ? allProFeatures : [];

const payload = {
  licenseId: randomUUID(),
  email: args.email,
  plan,
  seats: args.seats ? Number(args.seats) : 1,
  issuedAt: Date.now(),
  expiresAt: args.days ? Date.now() + Number(args.days) * 24 * 60 * 60 * 1000 : null,
  features,
};

const header = { alg: "Ed25519", v: 1 };

function b64url(buf) {
  return buf.toString("base64").replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

const headerB64 = b64url(Buffer.from(JSON.stringify(header), "utf8"));
const payloadB64 = b64url(Buffer.from(JSON.stringify(payload), "utf8"));
const signedData = Buffer.from(`${headerB64}.${payloadB64}`, "utf8");
const signature = cryptoSign(null, signedData, privateKey);
const licenseKey = `${headerB64}.${payloadB64}.${b64url(signature)}`;

console.log("License payload:\n");
console.log(JSON.stringify(payload, null, 2));
console.log("\nLicense key (paste into Wharf's Settings → License → Activate):\n");
console.log(licenseKey);
