/**
 * Public key used to verify signed Pro license keys.
 *
 * This is a DEV key generated by `npm run license:generate-keys` for this
 * starter so licensing works out of the box in development. Its matching
 * private key lives at keys/license-signing-key.private.json (gitignored,
 * not shipped). Before a real release:
 *
 *   1. Run `npm run license:generate-keys` again on a machine you trust
 *      (ideally wherever you'll run license issuance / your license server).
 *   2. Replace LICENSE_PUBLIC_KEY_PEM below with the new public key.
 *   3. Keep the new private key off of any machine that ships this app.
 */
export const LICENSE_PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEARtKoT1052M+SdSsQgXHDzXeZUZNOTcNDkHl0Lp1uuvg=
-----END PUBLIC KEY-----`;
